export { AltaDog } from './AltaDog/index.jsx'
export { Dogs } from './Dogs/index.jsx'
export { SearchDog } from './SearchDog/index.jsx'
export { BtnHome } from './BtnHome/index.jsx'
export { LogoLengua} from './LogoLengua/index.jsx'