export { AltaDog } from './AltaDog/index.jsx'
export { EditDog } from './EditDog/index.jsx'
export { Dogs } from './Dogs/index.jsx'
export { SearchDog } from './SearchDog/index.jsx'
export { BtnHome } from './BtnHome/index.jsx'
export { BtnTop } from './BtnTop/index.jsx'
export { LogoLengua} from './LogoLengua/index.jsx'
export { Footer } from './Footer/index.jsx'
export { AlertDogTime } from './AlertDogTime/index.jsx'
export { Navbar } from './Navbar/index.jsx'
export { AgendaDogs } from './AgendaDogs/index.jsx'
export { NuestraFormacion } from './nuestraFormacion/index.jsx'
export { NuestroSalon } from './nuestroSalon/index.jsx'
export { NuestrosServicios } from './nuestrosServicios/index.jsx'
export { TrabajosYTestimonios } from './trabajosYTestimonios/index.jsx'