export { AltaDog } from './AltaDog/index.jsx'
export { EditDog } from './EditDog/index.jsx'
export { Dogs } from './Dogs/index.jsx'
export { SearchDog } from './SearchDog/index.jsx'
export { BtnHome } from './BtnHome/index.jsx'
export { BtnTop } from './BtnTop/index.jsx'
export { LogoLengua} from './LogoLengua/index.jsx'
export { Footer } from './Footer/index.jsx'